# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven with Junit 5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  maven-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and run tests with Maven
      run: mvn clean test
      
    - name: test report
      uses: ScaCap/action-surefire-report@v1.0.5
      with:
        check_name: Maven Test Summary Report
        github_token: ${{ github.token }}
        report_paths: "target/surefire-reports/TEST-*.xml"
            
    - name: Upload Screenshots
      uses: actions/upload-artifact@v2
      with:
        name: Screenshots
        path: "screenshots/*"   
           